//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2Q3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EmpNo { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> designation { get; set; }
        public Nullable<int> dept { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual dept dept1 { get; set; }
        public virtual desg desg { get; set; }
    }
}
